all: PayableInterfaceTest.class
PayableInterfaceTest.class: PayableInterfaceTest.java
	javac PayableInterfaceTest.java
clean:
	rm -f *.class
run: PayableInterfaceTest.class
	java PayableInterfaceTest

